hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3307/untitled18_db
hibernate.connection.username=root
hibernate.connection.password=root1234
hibernate.connection.pool_size=10
hibernate.connection.autocommit=true