spring.application.name=url-shortener

spring.datasource.url=jdbc:postgresql://localhost:5433/urlshortener?options=-c%20TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=postgres1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

jwt.secret=${JWT_SECRET:change-this-to-a-very-long-random-secret-key-min-32-bytes}
jwt.expiration-ms=86400000